In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for i in range(10): my_arr2 = my_arr * 2
# Array's in Python are far more efficient in storing data than List
#This is because array operations are Vectorised, so looping thro is not required. 
#This makes the whole array operation more fast.

Wall time: 30.9 ms


In [5]:
%time for i in range(10): my_list2 = [x*2 for x in my_list]
# List's in Python are far LESS efficient in storing data than Array's

Wall time: 1.55 s


In [6]:
#4.1 The NumPy ndarray: A Multidimensional Array Object
data = np.random.randn(2,3)

In [7]:
#This gives the number of Rows and Columns in an array object. In this example, there are 2 Rows and 3 Cols
data.shape

(2, 3)

In [8]:
#Data type of the Array
data.dtype

dtype('float64')

In [9]:
data

array([[-0.46425295,  0.04836353, -0.10281422],
       [-0.26822431,  1.07161819, -2.27874498]])

In [10]:
#Array operation has a similar syntax as scalar operations
#Array multiplication
data *10

array([[ -4.64252955,   0.48363528,  -1.02814216],
       [ -2.68224312,  10.71618186, -22.78744976]])

In [11]:
#Array addition
data + data

array([[-0.92850591,  0.09672706, -0.20562843],
       [-0.53644862,  2.14323637, -4.55748995]])

In [12]:
#Creating a 1 Dimensional Arrays
data1 = [1,2,3,4,5,6]

In [13]:
arry1 = np.array(data1) #this creates a 1 dimensional array

In [14]:
arry1.shape #This gives the # Rows and # Cols in an Array. Here 6 is the total # of records in the 1D array

(6,)

In [15]:
arry1.ndim #This confirms the Dimension of an array

1

In [16]:
#Creating a 2 Dimensional Array
data2 = [[1,2,3,4],[5,6,7,8]]

In [17]:
arry2 = np.array(data2)

In [18]:
arry2.shape #there are 2 rows and three columns in this array

(2, 4)

In [19]:
arry2.ndim #The output is an 1 Dimensional Array

2

In [20]:
arry2.dtype #This gives the data type of the Array

dtype('int32')

In [21]:
#Numpy Zeros and Ones
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
type(np.zeros(10))

numpy.ndarray

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((10,2))
#The above creates a 10 * 2 array of ones
#Note: The shape of the array is provided with an extra parenthesis. 
#The following would result in error np.ones(10,2). The extra parenthesis is necessary. np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
np.empty((2,8,3),dtype = np.float64)
#This creates an empty array of shape (2,8,3). Here dtype is an optional argument, that can be used to force data type.
#NOTE: The empty array doesn't always create a NULL array. It just creates an array with random values[mostly close to 0]

array([[[1.08497750e-311, 1.08500141e-311, 2.13452202e-312],
        [0.00000000e+000, 1.69484279e-319, 2.13452201e-312],
        [0.00000000e+000, 1.08501111e-311, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 1.08501130e-311],
        [2.96439388e-323, 6.95264430e-310, 2.02369289e-320],
        [2.96439388e-323, 6.95264430e-310, 9.88131292e-324],
        [0.00000000e+000, 0.00000000e+000, 1.35587423e-318],
        [0.00000000e+000,             nan, 0.00000000e+000]],

       [[4.67296746e-307, 1.69121096e-306, 1.15710971e-306],
        [7.56587585e-307, 1.37961302e-306, 1.05699242e-307],
        [8.01097889e-307, 1.78020169e-306, 7.56601165e-307],
        [1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
        [1.33511018e-306, 6.23057689e-307, 1.86921279e-306],
        [8.90098127e-307, 1.78020848e-306, 1.60219035e-306],
        [1.42418172e-306, 2.04712906e-306, 7.56589622e-307],
        [1.11258277e-307, 8.90111708e-307, 0.00000000e+000]]])

In [26]:
#arange: This is the "range" equivalent for arrays. The resulting datatype is an array
# list(range(10)) #This would create a list of values from 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#Creating a Numpy array using arange function. The arguments for this function are Starting number, ending number+1, steps
np.arange(5,10,1)

array([5, 6, 7, 8, 9])

In [28]:
#Creating an identity array[1's in the diagonal and 0's in other places]. This always creates a N * N square Array
#Method 1
np.eye(10,dtype = np.int32)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [29]:
#Creating an identity array[1's in the diagonal and 0's in other places]. This always creates a N * N square Array
#Method 2
iden = np.identity(10,dtype = np.int32) #Here dtype is optional. It can take np.int32 or np.float64
iden

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [30]:
np.ones_like(iden) #If required to create a ones matrix in the shape of another array use ones_like

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [31]:
np.zeros_like(iden,dtype = np.float64) #If required to create a zeros matrix in the shape of another array use zeros_like

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.asarray(list(range(10))) #This creates a non array like input into an ndarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.asarray(list(range(10)),dtype = np.float64) #Externally forcing the data type to float using the dtype argument

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
np.asarray([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]).shape #Using a list of list as input and checking the shape using shape object

(4, 3)

In [35]:
np.asarray([((1,2,3),(4,5,6),(7,8,9)),((1,2,3),(4,5,6),(7,8,9))]).ndim #Using a list of tuple of tuple & checking dimension

3

In [36]:
#Data Types in NumPy

#Converting an array of one data type to another data type
data1 = list(range(1,11))
arr1 = np.array(data1)
print("Printing the Integer Array :",arr1)

float_arr1 = arr1.astype(np.float64)
print("Printing the Floating Array :",float_arr1)

Printing the Integer Array : [ 1  2  3  4  5  6  7  8  9 10]
Printing the Floating Array : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [37]:
#Using Data type attributes of another array
data2 = ['1.2','1.5','1.9','2.4']
string_arr1 = np.array(data2)
print("Printing the String Array :",string_arr1)
print("\n")

#NOTE: A String array[looking like Floating numbers] can be directly converted to a Floating Array
#but cannot be directly coverted to Integer
float_arr2 = string_arr1.astype(float_arr1.dtype)
print("Printing the Float array converted using data type of another array :",float_arr2)
print("\n")

int_arr2 = float_arr2.astype(arr1.dtype)
print("Printing an Int array converted using data type of another array :",int_arr2)
print("\n")

Printing the String Array : ['1.2' '1.5' '1.9' '2.4']


Printing the Float array converted using data type of another array : [1.2 1.5 1.9 2.4]


Printing an Int array converted using data type of another array : [1 1 1 2]




In [38]:
#Just rechecking the shape of an array created using arange function. This is already discussed earlier
np.arange(10).shape

(10,)

In [39]:
#Operations between Arrays and Scalars
#Vectorization = Making an element wise operation without the need for a "for Loop"
# Array operations are vectorised by default and wouldn't need any for loop and are very fast in executing
arr3 = np.array([[1,2,3],[4 ,5,  6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
#Product of an array with itself results in the square of the array
# An operation between two arrays of similar size or between an Array & a scalar are performed element wise[AKA vectorised]
arr3 * arr3

array([[ 1,  4,  9],
       [16, 25, 36]])

In [41]:
#Product of an array with scalar results in the product of the array
# An operation between two arrays of similar size or between an Array & a scalar are performed element wise[AKA vectorised]
arr3 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [42]:
#Array raised to its own power would result in n**n for each element in the array. [again vectorised ] 
#e.g., In the above case the result would be - 1**1, 2**2, 3**3, 4**4, 5**5 and 6**6
arr3 ** arr3

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

In [43]:
#Operation between two differently sized arrays is called broadcasting. 
#Broadcasting would be discussed in Chap 12

In [44]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr4_slice = arr4[4:7]
arr4_slice

array([4, 5, 6])

In [46]:
#-------------------------
#Array Slices are Views to the original Array. Any change to an Array slice would impact the original Array.
#-------------------------

#Updating an array slice here and this would result in the original array getting impacted

print("Before making a change to an array slice, the original array looked like this",arr4,".\n")

arr4_slice[:] = 64
print("The number of dimension of the sliced 3D array is ",arr4_slice.ndim)
print("After making a change to an array slice, the original array looks like this",arr4)


Before making a change to an array slice, the original array looked like this [0 1 2 3 4 5 6 7 8 9] .

The number of dimension of the sliced 3D array is  1
After making a change to an array slice, the original array looks like this [ 0  1  2  3 64 64 64  7  8  9]


In [47]:
# IF you want to impact only the array and NOT the original array, then you may need to explicity do a copy
arr4_slice_copy = arr4[4:7].copy()
arr4_slice_copy

# Now if we make any chnage to the slice, it would only impact the slice and NOT the original array
print("Before making a change to a copied array slice, the original array looked like this --->",arr4)
print("Before making a change to a copied array slice, the copied array_slice looked like this --->",arr4_slice_copy,"\n")

#Chnaging the values of arr4_slice_copy to 128
#Note: The syntax for changing all the elements in one go is to use array_name[:]
arr4_slice_copy[:] = 128

print("After making a change to a copied array, the original array looks like this --->",arr4)
print("After making a change to a copied array, the copied array_slice looked like this --->",arr4_slice_copy,"\n")

Before making a change to a copied array slice, the original array looked like this ---> [ 0  1  2  3 64 64 64  7  8  9]
Before making a change to a copied array slice, the copied array_slice looked like this ---> [64 64 64] 

After making a change to a copied array, the original array looks like this ---> [ 0  1  2  3 64 64 64  7  8  9]
After making a change to a copied array, the copied array_slice looked like this ---> [128 128 128] 



In [48]:
#Indexing ans Slicing for Multi Dimensional Arrays
#Note: The overall logic would still remain the same for 1D or nD arrays. 

#Creating a 2D array arr2d
arr2d = np.array([[1,2,3],[4,5,6]])

#Slicing the 2D array in a var
#Note: We here slice the 2D array using the index number 0. This would result in a 1D array [1,2,3]
arr2d_slice = arr2d[0]
print("The sliced 2D array before edit is ",arr2d_slice)
print("The number of dimension of the sliced 2D array is ",arr2d_slice.ndim)
print("The original 2D array before edit is ",arr2d,"\n")


#Accessing the values through indexing
print("Trying to print the value at the 0th index of a 2D array",arr2d[0])
print("Trying to print the value at 2nd position of the 0th index",arr2d[0,2],"\n")

#Changing the values in the sliced 2D array.
#Note: Since we didn't copy explicitly, any change to slice would change the original array
arr2d_slice[:] = 12
print("The sliced 2D array after edit is ",arr2d_slice)
print("The original 2D array after edit is ",arr2d,"\n")

#Creating a 3D array arr3d
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

#slicing the 3D array in a var
#Note: We here slice the 3D array using the index number 0. This would result in a 2D array [[1,2,3],[4,5,6]]
arr3d_slice = arr3d[0]
print("The sliced 3D array before edit is ",arr3d_slice)
print("The number of dimension of the sliced 3D array is ",arr3d_slice.ndim)
print("The original 3D array before edit is ",arr3d,"\n")

#Chnaging the values in the sliced 3D array
arr3d_slice[:] = 12 #This would replace all the elements of the sliced array with 12

print("The sliced 3D array after edit is ",arr3d_slice)
print("The original 3D array after edit is ",arr3d,"\n")

The sliced 2D array before edit is  [1 2 3]
The number of dimension of the sliced 2D array is  1
The original 2D array before edit is  [[1 2 3]
 [4 5 6]] 

Trying to print the value at the 0th index of a 2D array [1 2 3]
Trying to print the value at 2nd position of the 0th index 3 

The sliced 2D array after edit is  [12 12 12]
The original 2D array after edit is  [[12 12 12]
 [ 4  5  6]] 

The sliced 3D array before edit is  [[1 2 3]
 [4 5 6]]
The number of dimension of the sliced 3D array is  2
The original 3D array before edit is  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

The sliced 3D array after edit is  [[12 12 12]
 [12 12 12]]
The original 3D array after edit is  [[[12 12 12]
  [12 12 12]]

 [[ 7  8  9]
  [10 11 12]]] 



In [49]:
#Passing multiple indexes using the : command
#The : would be used in the similar manner python would work in other functions

#Creating a 2D array
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

#Indexing using : - Here we are slicing the nested list at 1st and afterwards [1:]. Then within the sliced list, we are slicing till 2nd [excluding 2nd]
x = arr2d[1:, :2]
print("The dimensions of the slice is",x.ndim)
print("The shape of the slice is",x.shape)
print("The actual slice of the array is",x)

The dimensions of the slice is 2
The shape of the slice is (2, 2)
The actual slice of the array is [[4 5]
 [7 8]]


In [50]:
#Feb 03 2023
#Boolean Indexing

#Creating a numpy array of names
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

#Creating a random normally distributed array
data = np.random.rand(7,4)
print(data,"\n")


#Converting the names array into a Boolean array using the comparison operator ==
#Note: Just like arithmetic operations, this also results in vectorisation [operation is performed on every element]
names == 'Bob'
print(names == 'Bob',"\n")

#Simple slicing the data array using Boolean array
#Note: The names array has 7 elements, so the data array has to have 7 rows. 
#If this conition is not met, then it would result in error
data[names == 'Bob']


#slicing using indexing
print(data[names == 'Bob',3].ndim,"- Dimension(s) of the boolean sliced array\n")
print(data[names == 'Bob',3].shape,"- Shape of the boolean sliced array\n")
print(data[names == 'Bob',3],"- boolean sliced array\n")

[[0.85992082 0.55881178 0.69657572 0.04176443]
 [0.81234974 0.22051535 0.98159811 0.19907462]
 [0.85775533 0.12952943 0.5154677  0.18334952]
 [0.87030852 0.486715   0.8218034  0.60521851]
 [0.49532362 0.16279047 0.87367724 0.89885616]
 [0.26376062 0.28689316 0.35440001 0.29959402]
 [0.89481065 0.38784937 0.01320006 0.76886412]] 

[ True False False  True False False False] 

1 - Dimension(s) of the boolean sliced array

(2,) - Shape of the boolean sliced array

[0.04176443 0.60521851] - boolean sliced array



In [51]:
#Travelling thro' array using for loop would result in row wise operation
for rows in data:
    print(rows.shape)

(4,)
(4,)
(4,)
(4,)
(4,)
(4,)
(4,)


In [52]:
#combining multiple arithmentic operations using the names array
print((names == 'Bob' )|(names == 'Joe'))
data[(names == 'Bob' )|(names == 'Joe')]

[ True  True False  True False  True  True]


array([[0.85992082, 0.55881178, 0.69657572, 0.04176443],
       [0.81234974, 0.22051535, 0.98159811, 0.19907462],
       [0.87030852, 0.486715  , 0.8218034 , 0.60521851],
       [0.26376062, 0.28689316, 0.35440001, 0.29959402],
       [0.89481065, 0.38784937, 0.01320006, 0.76886412]])

In [53]:
#We can negate a condition using either != or ~
names != 'Bob'
~(names == 'Bob')
print(data[~(names == 'Bob')],"\n")

#assigning the negated array to a variable
#Both the print statements would result in the same output
x = ~(names == 'Bob')
print(data[x],"\n")

[[0.81234974 0.22051535 0.98159811 0.19907462]
 [0.85775533 0.12952943 0.5154677  0.18334952]
 [0.49532362 0.16279047 0.87367724 0.89885616]
 [0.26376062 0.28689316 0.35440001 0.29959402]
 [0.89481065 0.38784937 0.01320006 0.76886412]] 

[[0.81234974 0.22051535 0.98159811 0.19907462]
 [0.85775533 0.12952943 0.5154677  0.18334952]
 [0.49532362 0.16279047 0.87367724 0.89885616]
 [0.26376062 0.28689316 0.35440001 0.29959402]
 [0.89481065 0.38784937 0.01320006 0.76886412]] 



In [54]:
#Setting values of array elements using boolean conditions

#Checking for a condition is a vectorised operation as we say earlier, operation is performed on the entire array
data < 0.45
print(data<0.45)

#subsetting is also vectorised as we saw earlier
data[data < 0.45]

#assigning values using above is also vectorised
data[data < 0.45] = 0.45
print(data)

[[False False False  True]
 [False  True False  True]
 [False  True False  True]
 [False False False False]
 [False  True False False]
 [ True  True  True  True]
 [False  True  True False]]
[[0.85992082 0.55881178 0.69657572 0.45      ]
 [0.81234974 0.45       0.98159811 0.45      ]
 [0.85775533 0.45       0.5154677  0.45      ]
 [0.87030852 0.486715   0.8218034  0.60521851]
 [0.49532362 0.45       0.87367724 0.89885616]
 [0.45       0.45       0.45       0.45      ]
 [0.89481065 0.45       0.45       0.76886412]]


In [55]:
a = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
print("The shape of the array is :",a.shape,"\n")
print("The dimensions of the array is :",a.ndim, "\n")

The shape of the array is : (2, 2, 5) 

The dimensions of the array is : 3 



In [56]:
#Feb 05 2023: Fancy Indexing
#In this section we can some fancy indexing
arr_fancy = np.empty((8,4))
arr_fancy.shape[0] #Will get the number of Rows
arr_fancy.shape[1] #Will get the number of Columns

for i in range(0,arr_fancy.shape[0]):
    arr_fancy[i] = i #Here we are using the indexing to assign values to individual elements of the array
print()
print(arr_fancy)



[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [57]:
#To access the array in a specific order, provide the indexing in the order of choice
#Note: Observe the extra square brackets that are used. If we ommit the extra square brackets, we may get a different output
arr_fancy[[1,2,5,4]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.],
       [4., 4., 4., 4.]])

In [58]:
#we can also write the array element twice to get a repititon as below
arr_fancy[[4,1,2,5,4]]

array([[4., 4., 4., 4.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.],
       [4., 4., 4., 4.]])

In [59]:
#We can use combination of negative indexing as well as positive indexing in the same command
arr_fancy[[-1,-2,3]]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [3., 3., 3., 3.]])

In [78]:
#Feb 07 2023: Fancy Indexing
#In this section we continue with fancy indexing
#To re-order both Rows and Columns using slicing then we may need to use the following syntax
#Note: Method 1
arr_fancy = np.arange(32).reshape((8,4))
print("Original Array before any slicing or indexing ")
print(arr_fancy)
print()

print("Output without taking care of the nuance, the output is not what we would expect")
print(arr_fancy[[1,3,5,7],[3,2,1,0]])
print()

print("Output using method 1: ")
print(arr_fancy[[1,3,5,7]][:,[3,2,1,0]])
print()

#Note: Method 2
print("Output using method 2: ")
print(arr_fancy[np.ix_([1,3,5,7],[3,2,1,0])])

Original Array before any slicing or indexing 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

Output without taking care of the nuance, the output is not what we would expect
[ 7 14 21 28]

Output using method 1: 
[[ 7  6  5  4]
 [15 14 13 12]
 [23 22 21 20]
 [31 30 29 28]]

Output using method 2: 
[[ 7  6  5  4]
 [15 14 13 12]
 [23 22 21 20]
 [31 30 29 28]]


In [84]:
#Transposing an Array
arr =np.arange(15).reshape((3,5))

print(arr)
print()

print(arr.T)
print()

print(arr)
print()

print(np.dot(arr,arr.T))
print()

print(np.dot(arr.T,arr))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]

[[125 140 155 170 185]
 [140 158 176 194 212]
 [155 176 197 218 239]
 [170 194 218 242 266]
 [185 212 239 266 293]]


In [103]:
arr = np.arange(16).reshape((2,2,4))
print(arr)
print(arr.shape)
print()

#The arguments of this function s nothing but the shape number. The elements in the argument that are passed are swapped
print(arr.swapaxes(1,2))

#The above command swaps the 1th and 2th elements and keeps the 0th same.
#Actual shape is [2,2,4]. After the above swap, the resulting shape would be [2,4,2].
#The resulting array would be 2 * [4 * 2] arrays from the original 2 * [2 * 4] arrays

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
(2, 2, 4)

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
