In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for i in range(10): my_arr2 = my_arr * 2
# Array's in Python are far more efficient in storing data than List

Wall time: 16 ms


In [5]:
%time for i in range(10): my_list2 = [x*2 for x in my_list]
# List's in Python are far LESS efficient in storing data than Array's

Wall time: 788 ms


In [6]:
#4.1 The NumPy ndarray: A Multidimensional Array Object
data = np.random.randn(2,3)

In [7]:
#This gives the number of Rows and Columns in an array object. In this example, there are 2 Rows and 3 Cols
data.shape

(2, 3)

In [21]:
#Data type of the Array
data.dtype

dtype('float64')

In [8]:
data

array([[ 0.6784212 ,  0.11511365, -0.54492264],
       [-1.35200529, -2.76919072, -0.88363296]])

In [9]:
#Array operation has a similar syntax as scalar operations
#Array multiplication
data *10

array([[  6.78421197,   1.15113654,  -5.44922635],
       [-13.52005291, -27.69190719,  -8.83632962]])

In [10]:
#Array addition
data + data

array([[ 1.35684239,  0.23022731, -1.08984527],
       [-2.70401058, -5.53838144, -1.76726592]])

In [13]:
#Creating a 1 Dimensional Arrays
data1 = [1,2,3,4,5,6]

In [16]:
arry1 = np.array(data1) #this creates a 1 dimensional array

In [18]:
arry1.shape #This gives the # Rows and # Cols in an Array. Here 6 is the total # of records in the 1D array

(6,)

In [19]:
arry1.ndim #This confirms the Dimension of an array

1

In [20]:
#Creating a 2 Dimensional Array
data2 = [[1,2,3,4],[5,6,7,8]]

In [21]:
arry2 = np.array(data2)

In [22]:
arry2.shape #there are 2 rows and three columns in this array

(2, 4)

In [23]:
arry2.ndim #The output is an 1 Dimensional Array

2

In [24]:
arry2.dtype #This gives the data type of the Array

dtype('int32')