In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for i in range(10): my_arr2 = my_arr * 2
# Array's in Python are far more efficient in storing data than List
#This is because array operations are Vectorised, so looping thro is not required. 
#This makes the whole array operation more fast.

Wall time: 22 ms


In [5]:
%time for i in range(10): my_list2 = [x*2 for x in my_list]
# List's in Python are far LESS efficient in storing data than Array's

Wall time: 909 ms


In [6]:
#4.1 The NumPy ndarray: A Multidimensional Array Object
data = np.random.randn(2,3)

In [7]:
#This gives the number of Rows and Columns in an array object. In this example, there are 2 Rows and 3 Cols
data.shape

(2, 3)

In [8]:
#Data type of the Array
data.dtype

dtype('float64')

In [9]:
data

array([[-0.12277499, -0.42282563, -2.3524739 ],
       [-0.55132606, -1.15152754,  0.44434366]])

In [10]:
#Array operation has a similar syntax as scalar operations
#Array multiplication
data *10

array([[ -1.2277499 ,  -4.22825633, -23.52473895],
       [ -5.51326063, -11.5152754 ,   4.44343662]])

In [11]:
#Array addition
data + data

array([[-0.24554998, -0.84565127, -4.70494779],
       [-1.10265213, -2.30305508,  0.88868732]])

In [12]:
#Creating a 1 Dimensional Arrays
data1 = [1,2,3,4,5,6]

In [13]:
arry1 = np.array(data1) #this creates a 1 dimensional array

In [14]:
arry1.shape #This gives the # Rows and # Cols in an Array. Here 6 is the total # of records in the 1D array

(6,)

In [15]:
arry1.ndim #This confirms the Dimension of an array

1

In [16]:
#Creating a 2 Dimensional Array
data2 = [[1,2,3,4],[5,6,7,8]]

In [17]:
arry2 = np.array(data2)

In [18]:
arry2.shape #there are 2 rows and three columns in this array

(2, 4)

In [19]:
arry2.ndim #The output is an 1 Dimensional Array

2

In [20]:
arry2.dtype #This gives the data type of the Array

dtype('int32')

In [21]:
#Numpy Zeros and Ones
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
type(np.zeros(10))

numpy.ndarray

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((10,2))
#The above creates a 10 * 2 array of ones
#Note: The shape of the array is provided with an extra parenthesis. 
#The following would result in error np.ones(10,2). The extra parenthesis is necessary. np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
np.empty((2,8,3),dtype = np.float64)
#This creates an empty array of shape (2,8,3). Here dtype is an optional argument, that can be used to force data type.
#NOTE: The empty array doesn't always create a NULL array. It just creates an array with random values[mostly close to 0]

array([[[1.00103256e-311, 1.00106684e-311, 1.40467151e-312],
        [0.00000000e+000, 1.69484279e-319, 1.40467151e-312],
        [0.00000000e+000, 1.00106544e-311, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 1.00106581e-311],
        [2.96439388e-323, 6.95288143e-310, 2.02369289e-320],
        [2.96439388e-323, 6.95288144e-310, 9.88131292e-324],
        [0.00000000e+000, 0.00000000e+000, 1.35587423e-318],
        [0.00000000e+000,             nan, 0.00000000e+000]],

       [[4.67296746e-307, 1.69121096e-306, 1.15710971e-306],
        [7.56587585e-307, 1.37961302e-306, 1.05699242e-307],
        [8.01097889e-307, 1.78020169e-306, 7.56601165e-307],
        [1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
        [1.33511018e-306, 6.23057689e-307, 1.86921279e-306],
        [8.90098127e-307, 1.78020848e-306, 1.60219035e-306],
        [1.42418172e-306, 2.04712906e-306, 7.56589622e-307],
        [1.11258277e-307, 8.90111708e-307, 0.00000000e+000]]])

In [26]:
#arange: This is the "range" equivalent for arrays. The resulting datatype is an array
# list(range(10)) #This would create a list of values from 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#Creating a Numpy array using arange function. The arguments for this function are Starting number, ending number+1, steps
np.arange(5,10,1)

array([5, 6, 7, 8, 9])

In [28]:
x

NameError: name 'x' is not defined

In [29]:
#Creating an identity array[1's in the diagonal and 0's in other places]. This always creates a N * N square Array
#Method 1
np.eye(10,dtype = np.int32)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [30]:
#Creating an identity array[1's in the diagonal and 0's in other places]. This always creates a N * N square Array
#Method 2
iden = np.identity(10,dtype = np.int32) #Here dtype is optional. It can take np.int32 or np.float64
iden

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [31]:
np.ones_like(iden) #If required to create a ones matrix in the shape of another array use ones_like

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [32]:
np.zeros_like(iden,dtype = np.float64) #If required to create a zeros matrix in the shape of another array use zeros_like

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.asarray(list(range(10))) #This creates a non array like input into an ndarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.asarray(list(range(10)),dtype = np.float64) #Externally forcing the data type to float using the dtype argument

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
np.asarray([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]).shape #Using a list of list as input and checking the shape using shape object

(4, 3)

In [36]:
np.asarray([((1,2,3),(4,5,6),(7,8,9)),((1,2,3),(4,5,6),(7,8,9))]).ndim #Using a list of tuple of tuple & checking dimension

3

In [37]:
#Data Types in NumPy

#Converting an array of one data type to another data type
data1 = list(range(1,11))
arr1 = np.array(data1)
print("Printing the Integer Array :",arr1)

float_arr1 = arr1.astype(np.float64)
print("Printing the Floating Array :",float_arr1)

Printing the Integer Array : [ 1  2  3  4  5  6  7  8  9 10]
Printing the Floating Array : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [38]:
#Using Data type attributes of another array
data2 = ['1.2','1.5','1.9','2.4']
string_arr1 = np.array(data2)
print("Printing the String Array :",string_arr1)
print("\n")

#NOTE: A String array[looking like Floating numbers] can be directly converted to a Floating Array
#but cannot be directly coverted to Integer
float_arr2 = string_arr1.astype(float_arr1.dtype)
print("Printing the Float array converted using data type of another array :",float_arr2)
print("\n")

int_arr2 = float_arr2.astype(arr1.dtype)
print("Printing an Int array converted using data type of another array :",int_arr2)
print("\n")

Printing the String Array : ['1.2' '1.5' '1.9' '2.4']


Printing the Float array converted using data type of another array : [1.2 1.5 1.9 2.4]


Printing an Int array converted using data type of another array : [1 1 1 2]




In [39]:
#Just rechecking the shape of an array created using arange function. This is already discussed earlier
np.arange(10).shape

(10,)

In [40]:
#Operations between Arrays and Scalars
#Vectorization = Making an element wise operation without the need for a "for Loop"
# Array operations are vectorised by default and wouldn't need any for loop and are very fast in executing
arr3 = np.array([[1,2,3],[4 ,5,  6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
#Product of an array with itself results in the square of the array
# An operation between two arrays of similar size or between an Array & a scalar are performed element wise[AKA vectorised]
arr3 * arr3

array([[ 1,  4,  9],
       [16, 25, 36]])

In [42]:
#Product of an array with scalar results in the product of the array
# An operation between two arrays of similar size or between an Array & a scalar are performed element wise[AKA vectorised]
arr3 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [43]:
#Array raised to its own power would result in n**n for each element in the array. [again vectorised ] 
#e.g., In the above case the result would be - 1**1, 2**2, 3**3, 4**4, 5**5 and 6**6
arr3 ** arr3

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

In [44]:
#Operation between two differently sized arrays is called broadcasting. 
#Broadcasting would be discussed in Chap 12

In [45]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr4_slice = arr4[4:7]
arr4_slice

array([4, 5, 6])

In [47]:
#-------------------------
#Array Slices are Views to the original Array. Any change to an Array slice would impact the original Array.
#-------------------------

#Updating an array slice here and this would result in the original array getting impacted

print("Before making a change to an array slice, the original array looked like this",arr4,".\n")

arr4_slice[:] = 64
print("The number of dimension of the sliced 3D array is ",arr4_slice.ndim)
print("After making a change to an array slice, the original array looks like this",arr4)


Before making a change to an array slice, the original array looked like this [0 1 2 3 4 5 6 7 8 9] .

The number of dimension of the sliced 3D array is  1
After making a change to an array slice, the original array looks like this [ 0  1  2  3 64 64 64  7  8  9]


In [48]:
# IF you want to impact only the array and NOT the original array, then you may need to explicity do a copy
arr4_slice_copy = arr4[4:7].copy()
arr4_slice_copy

# Now if we make any chnage to the slice, it would only impact the slice and NOT the original array
print("Before making a change to a copied array slice, the original array looked like this --->",arr4)
print("Before making a change to a copied array slice, the copied array_slice looked like this --->",arr4_slice_copy,"\n")

#Chnaging the values of arr4_slice_copy to 128
#Note: The syntax for changing all the elements in one go is to use array_name[:]
arr4_slice_copy[:] = 128

print("After making a change to a copied array, the original array looks like this --->",arr4)
print("After making a change to a copied array, the copied array_slice looked like this --->",arr4_slice_copy,"\n")

Before making a change to a copied array slice, the original array looked like this ---> [ 0  1  2  3 64 64 64  7  8  9]
Before making a change to a copied array slice, the copied array_slice looked like this ---> [64 64 64] 

After making a change to a copied array, the original array looks like this ---> [ 0  1  2  3 64 64 64  7  8  9]
After making a change to a copied array, the copied array_slice looked like this ---> [128 128 128] 



In [49]:
#Indexing ans Slicing for Multi Dimensional Arrays
#Note: The overall logic would still remain the same for 1D or nD arrays. 

#Creating a 2D array arr2d
arr2d = np.array([[1,2,3],[4,5,6]])

#Slicing the 2D array in a var
#Note: We here slice the 2D array using the index number 0. This would result in a 1D array [1,2,3]
arr2d_slice = arr2d[0]
print("The sliced 2D array before edit is ",arr2d_slice)
print("The number of dimension of the sliced 2D array is ",arr2d_slice.ndim)
print("The original 2D array before edit is ",arr2d,"\n")


#Accessing the values through indexing
print("Trying to print the value at the 0th index of a 2D array",arr2d[0])
print("Trying to print the value at 2nd position of the 0th index",arr2d[0,2],"\n")

#Changing the values in the sliced 2D array.
#Note: Since we didn't copy explicitly, any change to slice would change the original array
arr2d_slice[:] = 12
print("The sliced 2D array after edit is ",arr2d_slice)
print("The original 2D array after edit is ",arr2d,"\n")

#Creating a 3D array arr3d
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

#slicing the 3D array in a var
#Note: We here slice the 3D array using the index number 0. This would result in a 2D array [[1,2,3],[4,5,6]]
arr3d_slice = arr3d[0]
print("The sliced 3D array before edit is ",arr3d_slice)
print("The number of dimension of the sliced 3D array is ",arr3d_slice.ndim)
print("The original 3D array before edit is ",arr3d,"\n")

#Chnaging the values in the sliced 3D array
arr3d_slice[:] = 12 #This would replace all the elements of the sliced array with 12

print("The sliced 3D array after edit is ",arr3d_slice)
print("The original 3D array after edit is ",arr3d,"\n")

The sliced 2D array before edit is  [1 2 3]
The number of dimension of the sliced 2D array is  1
The original 2D array before edit is  [[1 2 3]
 [4 5 6]] 

Trying to print the value at the 0th index of a 2D array [1 2 3]
Trying to print the value at 2nd position of the 0th index 3 

The sliced 2D array after edit is  [12 12 12]
The original 2D array after edit is  [[12 12 12]
 [ 4  5  6]] 

The sliced 3D array before edit is  [[1 2 3]
 [4 5 6]]
The number of dimension of the sliced 3D array is  2
The original 3D array before edit is  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

The sliced 3D array after edit is  [[12 12 12]
 [12 12 12]]
The original 3D array after edit is  [[[12 12 12]
  [12 12 12]]

 [[ 7  8  9]
  [10 11 12]]] 



In [50]:
#Passing multiple indexes using the : command
#The : would be used in the similar manner python would work in other functions

#Creating a 2D array
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

#Indexing using : - Here we are slicing the nested list at 1st and afterwards [1:]. Then within the sliced list, we are slicing till 2nd [excluding 2nd]
x = arr2d[1:, :2]
print("The dimensions of the slice is",x.ndim)
print("The shape of the slice is",x.shape)
print("The actual slice of the array is",x)

The dimensions of the slice is 2
The shape of the slice is (2, 2)
The actual slice of the array is [[4 5]
 [7 8]]


In [51]:
#Feb 03 2023
#Boolean Indexing

#Creating a numpy array of names
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

#Creating a random normally distributed array
data = np.random.rand(7,4)
print(data,"\n")


#Converting the names array into a Boolean array using the comparison operator ==
#Note: Just like arithmetic operations, this also results in vectorisation [operation is performed on every element]
names == 'Bob'
print(names == 'Bob',"\n")

#Simple slicing the data array using Boolean array
#Note: The names array has 7 elements, so the data array has to have 7 rows. 
#If this conition is not met, then it would result in error
data[names == 'Bob']


#slicing using indexing
print(data[names == 'Bob',3].ndim,"- Dimension(s) of the boolean sliced array\n")
print(data[names == 'Bob',3].shape,"- Shape of the boolean sliced array\n")
print(data[names == 'Bob',3],"- boolean sliced array\n")

[[0.61979222 0.04788526 0.84863465 0.04171261]
 [0.71330931 0.19124681 0.91403745 0.33441793]
 [0.37300866 0.98425061 0.61772204 0.88324613]
 [0.6409046  0.46865723 0.59996377 0.93719029]
 [0.53617501 0.59148002 0.87056374 0.92398212]
 [0.20557098 0.16444159 0.44040878 0.54995809]
 [0.17140163 0.93563619 0.62238583 0.39039613]] 

[ True False False  True False False False] 

1 - Dimension(s) of the boolean sliced array

(2,) - Shape of the boolean sliced array

[0.04171261 0.93719029] - boolean sliced array



In [52]:
#Travelling thro' array using for loop would result in row wise operation
for rows in data:
    print(rows.shape)

(4,)
(4,)
(4,)
(4,)
(4,)
(4,)
(4,)


In [53]:
#combining multiple arithmentic operations using the names array
print((names == 'Bob' )|(names == 'Joe'))
data[(names == 'Bob' )|(names == 'Joe')]

[ True  True False  True False  True  True]


array([[0.61979222, 0.04788526, 0.84863465, 0.04171261],
       [0.71330931, 0.19124681, 0.91403745, 0.33441793],
       [0.6409046 , 0.46865723, 0.59996377, 0.93719029],
       [0.20557098, 0.16444159, 0.44040878, 0.54995809],
       [0.17140163, 0.93563619, 0.62238583, 0.39039613]])

In [54]:
#We can negate a condition using either != or ~
names != 'Bob'
~(names == 'Bob')
print(data[~(names == 'Bob')],"\n")

#assigning the negated array to a variable
#Both the print statements would result in the same output
x = ~(names == 'Bob')
print(data[x],"\n")

[[0.71330931 0.19124681 0.91403745 0.33441793]
 [0.37300866 0.98425061 0.61772204 0.88324613]
 [0.53617501 0.59148002 0.87056374 0.92398212]
 [0.20557098 0.16444159 0.44040878 0.54995809]
 [0.17140163 0.93563619 0.62238583 0.39039613]] 

[[0.71330931 0.19124681 0.91403745 0.33441793]
 [0.37300866 0.98425061 0.61772204 0.88324613]
 [0.53617501 0.59148002 0.87056374 0.92398212]
 [0.20557098 0.16444159 0.44040878 0.54995809]
 [0.17140163 0.93563619 0.62238583 0.39039613]] 



In [55]:
#Setting values of array elements using boolean conditions

#Checking for a condition is a vectorised operation as we say earlier, operation is performed on the entire array
data < 0.45
print(data<0.45)

#subsetting is also vectorised as we saw earlier
data[data < 0.45]

#assigning values using above is also vectorised
data[data < 0.45] = 0.45
print(data)

[[False  True False  True]
 [False  True False  True]
 [ True False False False]
 [False False False False]
 [False False False False]
 [ True  True  True False]
 [ True False False  True]]
[[0.61979222 0.45       0.84863465 0.45      ]
 [0.71330931 0.45       0.91403745 0.45      ]
 [0.45       0.98425061 0.61772204 0.88324613]
 [0.6409046  0.46865723 0.59996377 0.93719029]
 [0.53617501 0.59148002 0.87056374 0.92398212]
 [0.45       0.45       0.45       0.54995809]
 [0.45       0.93563619 0.62238583 0.45      ]]


In [56]:
a = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
print("The shape of the array is :",a.shape,"\n")
print("The dimensions of the array is :",a.ndim, "\n")

The shape of the array is : (2, 2, 5) 

The dimensions of the array is : 3 



In [105]:
#Feb 05 2023: Fancy Indexing
#In this section we can some fancy indexing
arr_fancy = np.empty((8,4))
arr_fancy.shape[0] #Will get the number of Rows
arr_fancy.shape[1] #Will get the number of Columns

for i in range(0,arr_fancy.shape[0]):
    arr_fancy[i] = i #Here we are using the indexing to assign values to individual elements of the array
print()
print(arr_fancy)



[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [106]:
#To access the array in a specific order, provide the indexing in the order of choice
#Note: Observe the extra square brackets that are used. If we ommit the extra square brackets, we may get a different output
arr_fancy[[1,2,5,4]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [107]:
#we can also write the array element twice to get a repititon as below
arr_fancy[[4,1,2,5,4]]

array([[4., 4., 4., 4.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.],
       [4., 4., 4., 4.]])

In [108]:
#We can use combination of negative indexing as well as positive indexing in the same command
arr_fancy[[-1,-2,3]]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [3., 3., 3., 3.]])